In [2]:
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

In [ ]:
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
zeros_array = np.zeros((4, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones_array = np.ones((4, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
range_array = np.arange(0, 60, 4)
range_array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56])

In [ ]:
base_array = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

new_array = np.empty_like(base_array)

In [ ]:
class_a_scores = np.array([85, 90, 88, 92, 78])

class_b_scores = np.array([88, 92, 84, 90, 76])

In [ ]:
winner = "Class A" if np.mean(class_a_scores) > np.mean(class_b_scores) else "Class B"

print(f"The winner is: {winner}")

The winner is: Class A


In [ ]:
a = np.array([1, 2, 3])

b = np.negative(a)

print(b)

[-1 -2 -3]


In [4]:
array_a = np.array([1, 2, 3, 4,5,6,7,8])
array_b = np.array([5, 6, 7, 8,9,10,11,12])

addition_result = array_a + array_b

addition_result

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
multiplication_result = array_a * array_b

multiplication_result

array([ 5, 12, 21, 32, 45, 60, 77, 96])

In [7]:
mean_array_a = np.mean(array_a)

print(mean_array_a)

4.5


In [9]:
meadin_array_a = np.median(array_a)

print(median_array_a)

4.5


In [10]:
std_array_a = np.std(array_a)

print(std_array_a)

2.29128784747792


In [11]:
min_array_a = np.min(array_a)

print(min_array_a)

1


In [12]:
max_array_a = np.max(array_a)

print(max_array_a)

8


In [13]:
sum_array_a = np.sum(array_a)

print(sum_array_a)

36


In [14]:
prod_array_a = np.prod(array_a)

print(prod_array_a)

40320


In [15]:
var_array_a = np.var(array_a)

print(var_array_a)

5.25


In [20]:
percentile_array_a = np.percentile(array_a, q=100)  # q = 100 for 100th percentile

print(percentile_array_a)

8.0


In [1]:
import numpy as np
import pandas as pd

# Load the dataset
data = pd.read_csv('BHP.csv')
data.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [2]:
data = data.apply(pd.to_numeric, errors='coerce')
data.head()

area_type  availability  location  size  society  total_sqft  bath  \
0        NaN           NaN       NaN   NaN      NaN      1056.0   2.0   
1        NaN           NaN       NaN   NaN      NaN      2600.0   5.0   
2        NaN           NaN       NaN   NaN      NaN      1440.0   2.0   
3        NaN           NaN       NaN   NaN      NaN      1521.0   3.0   
4        NaN           NaN       NaN   NaN      NaN      1200.0   2.0   

   balcony   price  
0      1.0   39.07  
1      3.0  120.00  
2      3.0   62.00  
3      1.0   95.00  
4      1.0   51.00

In [3]:
# Drop rows with NaN values
# Fill NaN values with mean of each column
data.fillna(data.mean(), inplace=True)
data

area_type  availability  location  size  society  total_sqft  bath  \
0            NaN           NaN       NaN   NaN      NaN      1056.0   2.0   
1            NaN           NaN       NaN   NaN      NaN      2600.0   5.0   
2            NaN           NaN       NaN   NaN      NaN      1440.0   2.0   
3            NaN           NaN       NaN   NaN      NaN      1521.0   3.0   
4            NaN           NaN       NaN   NaN      NaN      1200.0   2.0   
...          ...           ...       ...   ...      ...         ...   ...   
13315        NaN           NaN       NaN   NaN      NaN      3453.0   4.0   
13316        NaN           NaN       NaN   NaN      NaN      3600.0   5.0   
13317        NaN           NaN       NaN   NaN      NaN      1141.0   2.0   
13318        NaN           NaN       NaN   NaN      NaN      4689.0   4.0   
13319        NaN           NaN       NaN   NaN      NaN       550.0   1.0   

        balcony   price  
0      1.000000   39.07  
1      3.000000  120.00  
2      3.000000   62.00  
3      1.000000   95.00  
4      1.000000   51.00  
...         ...     ...  
13315  0.000000  231.00  
13316  1.584376  400.00  
13317  1.000000   60.00  
13318  1.000000  488.00  
13319  1.000000   17.00  

[13320 rows x 9 columns]

In [4]:
X = data[['total_sqft','bath','balcony']]
y = data[['price']]

In [5]:
X_scaled = (X - np.mean(X, axis=0)) / np.std(X, axis=0) # scaling the features

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [7]:
# centering the data and ensuring that the features are on a comparable level

X_train_mean = np.mean(X_train, axis=0)
X_train_centered = X_train - X_train_mean

In [8]:
theta = np.dot(np.dot(np.linalg.inv(np.dot(X_train_centered.T, X_train_centered)), X_train_centered.T), y_train)
# this line of code computes the parameter vector theta using the OLS method(ordinal least squares)

In [9]:
X_test_centered = X_test - X_train_mean
y_pred = np.dot(X_test_centered, theta)
y_pred

array([[-48.40194702],
       [ 17.65652088],
       [-45.89759793],
       ...,
       [ 19.90765873],
       [-42.51811483],
       [ -9.89131905]])

In [10]:
X_test_centered

total_sqft      bath   balcony
8077    -0.417938 -0.520527 -0.736170
1602     0.103712  0.227010 -0.736170
10498   -0.377184 -0.520527 -0.736170
3297    -0.295676  0.974547  0.516444
8893     0.706055  0.227010 -0.736170
...           ...       ...       ...
1082    -0.866232 -1.268064 -0.736170
1671     0.193371  2.469620 -1.988784
4325     0.193371  0.227010  1.769058
7375    -0.295676 -0.520527  0.516444
5152    -0.344581  0.227010 -0.736170

[2664 rows x 3 columns]

In [12]:
nan_count = np.count_nonzero(np.isnan(y_pred))
print(f"Number of NaN values in y_pred: {nan_count}")

Number of NaN values in y_pred: 0


In [13]:
y_pred[np.isnan(y_pred)] = np.nanmean(y_pred)

In [14]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 23635.762101035038
